# coding utf-8

REQUEST_TYPE_IDENTIFIER_CHAT_MESSAGE_NEW = 'ChatMessageNewRequest'
REQUEST_TYPE_IDENTIFIER_CHAT_MESSAGE_EDIT = 'ChatMessageEditRequest'
REQUEST_TYPE_IDENTIFIER_MESSAGE_ERROR = 'ErrorMessageForDevelopers'
REQUEST_TYPE_IDENTIFIER_UPDATE = 'UpdateRequest'
REQUEST_TYPE_IDENTIFIER_EVENT = 'EventRequest'
REQUEST_TYPE_IDENTIFIER_SKYPE_STATE = 'SkypeStateRequest'

TYPE_IDENTIFIER_MESSAGE_USER_CHAT = 'ChatMessageUserChat'
TYPE_IDENTIFIER_MESSAGE_GROUP_CHAT = 'ChatMessageGroupChat'
TYPE_IDENTIFIER_MESSAGE_EDIT_MESSAGE = 'ChatMessageEdit'
TYPE_IDENTIFIER_CHAT_ADD_MEMBER = 'ChatAddMember'
TYPE_IDENTIFIER_CHAT_REMOVE_MEMBER = 'ChatRemoveMember'
TYPE_IDENTIFIER_CONTACT_ACCEPT_REQUEST = 'ContactAcceptRequest'
TYPE_IDENTIFIER_CONTACT_REJECT_REQUEST = 'ContactRejectRequest'

# not use here
REQUEST_TYPE_IDENTIFIER_CHAT_MESSAGE_FROM_BOT = 'ChatMessageFromBotRequest'

SERVICE_NAME_SKPY = 'Skpy'
